# Generated by Django 4.2.7 on 2024-01-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_addtrain'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shedule',
            new_name='Schedule',
        ),
    ]
