# Generated by Django 4.2.7 on 2024-01-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_rename_shedule_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtrain',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='train/media/'),
        ),
        migrations.AddField(
            model_name='train',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='train/media/'),
        ),
    ]
